apiVersion: v1
kind: Secret
metadata:
<<<<<<< HEAD
  name: {{ include "bookcatalog-chart.fullname" . }}-secret
  labels:
    {{- include "bookcatalog-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  djangoSecretKey: {{ .Values.secret.djangoSecretKey | quote }}
  githubToken:    {{ .Values.secret.githubToken    | quote }}
  github_fine_grained_token: {{ .Values.secret.github_fine_grained_token | quote }}
=======
  name: bookapi-secret
  namespace: dev
type: Opaque
stringData:
  GITHUB_TOKEN: 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
  SECRET_KEY: m+j^4fwe@z_b9odd*xpy!w&huy#vcoibu0od*!1^#-%dm+_0cw
>>>>>>> 9513ea1 (fixing chart to start fresh)
