# {{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookcatalog-serviceaccount
  labels:
    app: bookcatalog
  # {{- with .Values.serviceAccount.annotations }}
  # annotations:
  #   key: value
  # {{- end }}
automountServiceAccountToken: true
# {{- end }}
