#.github/workflows/full-pipeline.yaml
name: CI Pipeline with ArgoCD Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: 🔐 Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: 🔨 Build and push Docker image
        run: |
          IMAGE_TAG=ghcr.io/${{ secrets.GHCR_USERNAME }}/bookcatalog-app:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: pip install -r requirements.txt

      - name: 🧪 Run tests
        run: pytest api/tests.py

      - name: 📝 Update Helm values with new image tag
        run: |
          sed -i "s|repository:.*|repository: ghcr.io/${{ secrets.GHCR_USERNAME }}/bookcatalog-app|" bookcatalog-chart/values.yaml
          sed -i "s|tag:.*|tag: ${{ github.sha }}|" bookcatalog-chart/values.yaml

      - name: 📤 Commit updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add bookcatalog-chart/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push