# values.yaml

# Default number of replicas for your Deployment
replicaCount: 1

# Horizontal Pod Autoscaler settings
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80


# -------------------------------------------------------------------
# ServiceAccount settings
# -------------------------------------------------------------------
serviceAccount:
  # Create a ServiceAccount (true) or skip (false)
  create: false

  # If you set create: true, you can specify a custom name here.
  # Otherwise, Helm will generate one.
  name: ""
# -------------------------------------------------------------------
# Image settings
# -------------------------------------------------------------------

image:
  repository: ghcr.io/caduostudent/capstoneproject
  tag: main
  pullPolicy: IfNotPresent
# -------------------------------------------------------------------
# Image pull secrets
# -------------------------------------------------------------------

# If you use multiple secrets, list them here
imagePullSecrets:
  - name: capstone

# -------------------------------------------------------------------

# Service settings
# -------------------------------------------------------------------
service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

  app:
  command:
    - python
    - manage.py
    - runserver
    - 0.0.0.0:8000
