# bookcatalog-chart/templates/values.yaml

replicaCount: 1

image:
  repository: ghcr.io/caduostudent/capstoneproject
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: bookapi.local
      paths:
        - path: /
          pathType: Prefix

config:
  DJANGO_SETTINGS_MODULE: bookapi.settings
  DEBUG: "false"

secret:
  GITHUB_TOKEN: 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
  SECRET_KEY: m+j^4fwe@z_b9odd*xpy!w&huy#vcoibu0od*!1^#-%dm+_0cw
  github_fine_grained_token: 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
  

readinessProbe:
  enabled: true
  path: /api/health/
  port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /api/health/
  port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20