# values.yaml

# ------------------------------------------------
# Probe configuration
# ------------------------------------------------
readinessProbe:
  enabled: true
  path: /api/health/
  port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /api/health/
  port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20


# Default number of replicas for your Deployment
replicaCount: 1

# Horizontal Pod Autoscaler settings
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

migrations:
  enabled: true
# -------------------------------------------------------------------
# ServiceAccount settings
# -------------------------------------------------------------------
serviceAccount:
  # Create a ServiceAccount (true) or skip (false)
  create: false

  # If you set create: true, you can specify a custom name here.
  # Otherwise, Helm will generate one.
  name: ""
# -------------------------------------------------------------------
# Image settings
# -------------------------------------------------------------------

image:
  repository: ghcr.io/caduostudent/capstoneproject
  tag: main
  pullPolicy: IfNotPresent
# -------------------------------------------------------------------
# Image pull secrets
# -------------------------------------------------------------------

# If you use multiple secrets, list them here
imagePullSecrets:
  - name: capstone

# -------------------------------------------------------------------

# Service settings
# -------------------------------------------------------------------


ingress:
  enabled: true
  hosts:
    - host: bookapi.local
      paths: 
        - /
  tls:
    - hosts: 
        - "bookapi.local"
      secretName: bookapi-tls

service:
  port: 8000
# -------------------------------------------------------------------

app:
  command:
    - python
    - manage.py
    - runserver
    - 0.0.0.0:8000
