replicaCount: 1

image:
  repository: ghcr.io/caduostudent/capstoneproject
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: bookapi.local
      paths:
        - path: /
          pathType: Prefix

config:
  DJANGO_SETTINGS_MODULE: bookapi.settings
  DEBUG: "false"

secret:
  djangoSecretKey: "m+j^4fwe@z_b9odd*xpy!w&huy#vcoibu0od*!1^#-%dm+_0cw"
  githubToken:    "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"

readinessProbe:
  enabled: true
  path: /api/health/
  port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /api/health/
  port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20