name: CD to k3d Dev Cluster

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [ 'docker-build' ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d cluster create ct --servers 1 --agents 0

      - name: Install kubectl & Helm
        uses: azure/setup-kubectl@v3
      - uses: azure/setup-helm@v3

      - name: Create GHCR Secret in k3d
        run: |
          kubectl create secret docker-registry ghcr-creds \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }} \
            --namespace default || true

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install bookapi ./bookcatalog-chart \
            --namespace dev --create-namespace \
            -f values.dev.yaml