# .github/workflows/chart-testing.yml
on:
  workflow_call:
    inputs:
      chart-path:
        description: 'Path to the Helm chart directory'
        required: true
        type: string
        default: 'bookcatalog-chart'
      helm-version:
        description: 'Helm CLI version'
        required: false
        type: string
        default: 'v3.14.0'
      ct-version:
        description: 'chart-testing CLI version'
        required: false
        type: string
        default: '3.10.0'
    secrets:
      KUBE_CONFIG:
        description: 'Kubernetes config for real cluster installs'
        required: false

jobs:
  lint-and-test:
    name: Lint and Install Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ inputs.helm-version }}

      - name: Install chart-testing CLI
        run: |
          CT_VER="${{ inputs.ct-version }}"
          curl -sL \
            "https://github.com/helm/chart-testing/releases/download/v${CT_VER}/chart-testing_${CT_VER}_Linux_x86_64.tar.gz" \
            | tar xz
          sudo mv ct /usr/local/bin/

      - name: Lint Helm chart
        run: ct lint --charts "${{ inputs.chart-path }}"

      - name: Install chart in test namespace
        if: secrets.KUBE_CONFIG != ''
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          NAMESPACE="ct-test-${{ github.sha }}"
          kubectl create namespace "${NAMESPACE}" || true
          ct install \
            --charts "${{ inputs.chart-path }}" \
            --namespace "${NAMESPACE }}" \
            --skip-cleanup