name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  # 1. Lint your Helm chart
  chart-testing:
    uses: ./.github/workflows/chart-testing.yml

  # 2. Run Django tests
  django-tests:
    uses: ./.github/workflows/django-tests.yml

  # 3. Create a semantic release (runs .github/workflows/release.yml)
  release:
    uses: ./.github/workflows/release.yml

  # 4. Build & push Docker image
  build-docker-image:
    needs: [release]
    uses: ./.github/workflows/docker-build.yml
    with:
      # Provide the semantically-released version to your docker-build job
      image-tag: ${{ needs.release.outputs.new-release-version }}

  # 5. Bump Helm chart values and commit so Argo CD picks up the change
  deploy-application:
    name: Deploy Application via GitOps
    runs-on: ubuntu-latest
    needs:
      - release
      - build-docker-image
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump image.tag in Production values
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'envs/production/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ needs.release.outputs.new-release-version }}
          branch: main
          commitChange: true
          message: |
            chore: Deploy Image Version ${{ needs.release.outputs.new-release-version }} [skip ci]