# .github/workflows/django-tests.yml
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true
    secrets:
      POSTGRES_URL:
        description: "Optional test DB URL"
        required: false

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Django tests
        run: pytest