# .github/workflows/docker-build.yml
on:
  workflow_call:
    inputs:
      image-tag:
        description: "Tag for the Docker image"
        required: true
        type: string
    secrets:
      ghcr_token:
        description: "GHCR token (can be GHCR_TOKEN or a fine-grained PAT)"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.image-tag }}